// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3O0fhRBXWSe9WsSgWuZM-YuZERVZutM',
    appId: '1:55535795649:web:84c51196b361731bb30340',
    messagingSenderId: '55535795649',
    projectId: 'indoor-localization-7decb',
    authDomain: 'indoor-localization-7decb.firebaseapp.com',
    storageBucket: 'indoor-localization-7decb.firebasestorage.app',
    measurementId: 'G-FFP8W2Y1JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZQ-DSFRI9HawAqCpJET6EDqZK1FWDEM',
    appId: '1:55535795649:android:22fe45365fa6e6c5b30340',
    messagingSenderId: '55535795649',
    projectId: 'indoor-localization-7decb',
    storageBucket: 'indoor-localization-7decb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6Iw6wdD6AY9fbstTXk3GVB4MlqELYNU',
    appId: '1:55535795649:ios:f2559419c6d5d7cdb30340',
    messagingSenderId: '55535795649',
    projectId: 'indoor-localization-7decb',
    storageBucket: 'indoor-localization-7decb.firebasestorage.app',
    iosClientId: '55535795649-5cfjjriblnf3qub7obpuqkn6ghkqh8kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.g14IndoorLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB6Iw6wdD6AY9fbstTXk3GVB4MlqELYNU',
    appId: '1:55535795649:ios:f2559419c6d5d7cdb30340',
    messagingSenderId: '55535795649',
    projectId: 'indoor-localization-7decb',
    storageBucket: 'indoor-localization-7decb.firebasestorage.app',
    iosClientId: '55535795649-5cfjjriblnf3qub7obpuqkn6ghkqh8kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.g14IndoorLocator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf3O0fhRBXWSe9WsSgWuZM-YuZERVZutM',
    appId: '1:55535795649:web:d01276b72074a4e6b30340',
    messagingSenderId: '55535795649',
    projectId: 'indoor-localization-7decb',
    authDomain: 'indoor-localization-7decb.firebaseapp.com',
    storageBucket: 'indoor-localization-7decb.firebasestorage.app',
    measurementId: 'G-KP5HMKJZCC',
  );

}